# Generated by Django 2.2.16 on 2022-06-22 19:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0013_auto_20220622_2221'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
