# Generated by Django 2.2.16 on 2022-06-22 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0015_follow'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Follow',
        ),
    ]
